"""
SONIC-REDA — CodeFix Agent
============================
Automated secure remediation and code patch generation.

Responsibilities:
    - Generates minimal, robust, secure code fixes for verified vulnerabilities
    - Creates security unit test cases preventing regressions
    - Formats GitHub/GitLab Pull Request descriptions with impact analysis
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from sonic.agents.base import BaseAgent
from sonic.logger import get_logger

logger = get_logger(__name__)


@dataclass
class RemediationPackage:
    """Complete remediation package for a vulnerability."""
    finding_id: str
    patch_diff: str
    regression_tests: str
    pr_title: str
    pr_description: str
    remediation_summary: str


class CodeFixAgent(BaseAgent):
    """
    Agent dedicated to writing secure code fixes, unit tests, and PR descriptions.
    """

    def __init__(self, **kwargs: Any):
        super().__init__(name="CodeFixAgent", **kwargs)

    def get_system_prompt(self) -> str:
        return """You are the CodeFix & Remediation Agent of SONIC-REDA.

Your job is to generate production-grade, secure patches for identified vulnerabilities.

Rules:
1. MINIMAL PATCH: Make surgical fixes without altering unrelated business logic.
2. DEFENSIVE CODING: Use parameterized queries, context-aware escaping, proper authorization checks.
3. REGRESSION TESTS: Provide automated unit tests verifying the fix.
4. PULL REQUEST READY: Provide PR title and markdown description.

Return results as structured JSON."""

    async def run(self, task: dict[str, Any]) -> dict[str, Any]:
        """Generate remediation package for a vulnerability."""
        self.status = "running"
        finding = task.get("finding", {})
        code_context = task.get("code_context", "")

        pkg = await self._generate_fix(finding, code_context)
        self.status = "completed"

        return {
            "finding_id": pkg.finding_id,
            "patch_diff": pkg.patch_diff,
            "regression_tests": pkg.regression_tests,
            "pr_title": pkg.pr_title,
            "pr_description": pkg.pr_description,
            "summary": pkg.remediation_summary,
        }

    async def _generate_fix(self, finding: dict[str, Any], code_context: str) -> RemediationPackage:
        prompt = f"""Generate a secure remediation package for this vulnerability:

VULNERABILITY:
Title: {finding.get('title')}
Class: {finding.get('vulnerability_class')}
Description: {finding.get('description')}
PoC: {finding.get('poc')}

SOURCE CODE CONTEXT:
```
{code_context[:4000]}
```

Generate:
1. A unified git diff patch fixing the issue
2. Unit tests confirming the fix
3. Pull Request title and description

Return JSON:
{{
    "patch_diff": "diff --git a/file b/file\\n...",
    "regression_tests": "def test_security_fix(): ...",
    "pr_title": "Fix: [Vulnerability] in component",
    "pr_description": "## Overview\\nFixes CVE...",
    "remediation_summary": "Brief explanation of how the patch fixes the issue"
}}"""

        response = await self.think(prompt, task_type="coding")
        try:
            content = response.content
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0]
            elif "```" in content:
                content = content.split("```")[1].split("```")[0]
            data = json.loads(content)
            return RemediationPackage(
                finding_id=finding.get("uid", "fnd-01"),
                patch_diff=data.get("patch_diff", ""),
                regression_tests=data.get("regression_tests", ""),
                pr_title=data.get("pr_title", f"Fix: {finding.get('title')}"),
                pr_description=data.get("pr_description", "Automated security patch generated by SONIC-REDA"),
                remediation_summary=data.get("remediation_summary", "Applied defensive input validation & authorization check"),
            )
        except Exception as e:
            logger.error("codefix_parse_failed", finding=finding.get("uid", ""), error=str(e))
            return RemediationPackage(
                finding_id=finding.get("uid", "fnd-01"),
                patch_diff="",
                regression_tests="",
                pr_title=f"Security Patch: {finding.get('title')}",
                pr_description="Automated security patch generation failed — LLM did not return parseable JSON.",
                remediation_summary=f"CodeFix agent could not produce a patch (parse error: {str(e)[:200]}).",
            )
